// This file is autogenerated by Firebase Studio. Do not modify it manually.
import {initializeApp, getApp, getApps} from 'firebase/app';
import {getAuth} from 'firebase/auth';
import {getFirestore} from 'firebase/firestore';
import {getStorage} from 'firebase/storage';
import {getFunctions} from 'firebase/functions';

const firebaseConfig = {
  "projectId": "studio-1703865431-b7704",
  "appId": "1:702684370770:web:5275bec79f81b01fa1cc8b",
  "apiKey": "AIzaSyDwmUKJBhCUbAmv661lqbyCciPl3JSkDrU",
  "authDomain": "studio-1703865431-b7704.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "702684370770"
};

const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const firestore = getFirestore(app);
const auth = getAuth(app);
const storage = getStorage(app);
const functions = getFunctions(app);

export {app, firestore, auth, storage, functions};
