
// This file is autogenerated by Firebase Studio. Do not modify it manually.
import {initializeApp, getApp, getApps} from 'firebase/app';
import {getAuth} from 'firebase/auth';
import {getFirestore} from 'firebase/firestore';
import {getStorage} from 'firebase/storage';
import {getFunctions} from 'firebase/functions';

const firebaseConfig = {
  apiKey: "AIzaSyD65ANQJsxE5vMku9s6H4246aQkIHmxb4I",
  authDomain: "ranchat-bfd62.firebaseapp.com",
  projectId: "ranchat-bfd62",
  storageBucket: "ranchat-bfd62.appspot.com",
  messagingSenderId: "410411881052",
  appId: "1:410411881052:web:f6d95e9f52659148b20c99",
  measurementId: "G-0JTDLEWRM8"
};

const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const firestore = getFirestore(app);
const auth = getAuth(app);
const storage = getStorage(app);
const functions = getFunctions(app);

export {app, firestore, auth, storage, functions};
