// This file is autogenerated by Firebase Studio. Do not modify it manually.
import {initializeApp, getApp, getApps} from 'firebase/app';
import {getAuth} from 'firebase/auth';
import {getFirestore} from 'firebase/firestore';
import {getStorage} from 'firebase/storage';
import {getFunctions} from 'firebase/functions';

const firebaseConfig = {
  apiKey: 'TODO:REPLACE_WITH_YOUR_FIREBASE_API_KEY',
  authDomain: 'TODO:REPLACE_WITH_YOUR_FIREBASE_AUTH_DOMAIN',
  projectId: 'TODO:REPLACE_WITH_YOUR_FIREBASE_PROJECT_ID',
  storageBucket: 'TODO:REPLACE_WITH_YOUR_FIREBASE_STORAGE_BUCKET',
  messagingSenderId: 'TODO:REPLACE_WITH_YOUR_FIREBASE_MESSAGING_SENDER_ID',
  appId: 'TODO:REPLACE_WITH_YOUR_FIREBASE_APP_ID',
};

const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const firestore = getFirestore(app);
const auth = getAuth(app);
const storage = getStorage(app);
const functions = getFunctions(app);

export {app, firestore, auth, storage, functions};
